import { Schema } from 'mongoose'
import {
    AppointmentStore
} from '../../db'

const appointmentSchema = new Schema({
    appointmentid: String,
    consultdate: String,
    doctorid: String,
    doctorqualification: Array,
    status: String,
    timeid: Number,
    apdate: Date,
    treatmentid: String,
    diseaseid: String,
    contactperson: Object,
    ispaid: Boolean,
    patientid: String,
    name: String,
    promotionid: String,
    fee: Number,
    offerprice: Number,
    israted: Boolean,
    isrefund: Boolean,
    doctorname: String,
    email: String,
    createddate: Date,
    purpose: String,
    treatment: String,
    updateddate: Date,
    share: Array,
    orderhistory: Array,
    transid: String,
    banktransid: String,
    bankname: String,
    transdate: String,
    paymentmode: String,
    transrespcode: String,
    transrespmsg: String,
    refunid: String,
    refundtransid: String,
    refundtransdate: String,
    refundbanktransid: String,
    refundrespcode: String,
    refundtransrespmsg: String,
    refunddate: String,
    refundstatus: String,
    ismedordered: Boolean,
    isattachprescription: Boolean,
    reqid: String,
    isattachreport: Boolean,
    refundamt: Number,
    pharmacyid: String,
    ismedquotsent: Boolean,
    resolvedAt: Date,
    displayStatus: String,
    txnStatusErr: String,
    txnStatusAmt: Number,
    txnStatusOrd: String,
    txnStatusTxnId: String,
    txnStatusNotVerified: Boolean,
    actualFee: Number,
    consultationcoupon: Object,
    isCouponApplied: Boolean,
    isCorporate: Boolean,
    ismedreq: Boolean
})

const Appointment = AppointmentStore.model('Appointment', appointmentSchema);

export default Appointment;